export const REGIONS: Record<string, string[]> = {
  // 서울
  '서울특별시': [
    '강남구', '강동구', '강북구', '강서구', '관악구',
    '광진구', '구로구', '금천구', '노원구', '도봉구',
    '동대문구', '동작구', '마포구', '서대문구', '서초구',
    '성동구', '성북구', '송파구', '양천구', '영등포구',
    '용산구', '은평구', '종로구', '중 구', '중랑구',
  ],

  // 인천
  '인천광역시': [
    '계양구', '남동구', '동구', '미추홀구', '부평구',
    '서구', '연수구', '중구',
  ],

  // 경기 (구가 있는 도시만)
  '수원시': ['장안구', '권선구', '팔달구', '영통구'],
  '성남시': ['수정구', '중원구', '분당'],
  '안양시': ['만안구', '동안구'],
  '부천시': ['원미구', '소사구', '오정구'],
  '안산시': ['상록구', '단원구'],
  '고양시': ['덕양구', '일산동구', '일산서구'],
  '용인시': ['처인구', '기흥구', '수지구'],
  '화성시': ['동탄구', '만세구', '병점구', '효행구'],
}

export const DISTRICT_CATEGORY_MAP: Record<string, string> = {
    '종로구': 'JONGNO',
    '중구': 'JUNG',
    '용산구': 'YONGSAN',
    '성동구': 'SEONGDONG',
    '광진구': 'GWANGJIN',
    '동대문구': 'DONGDAEMUN',
    '중랑구': 'JUNGNANG',
    '성북구': 'SEONGBUK',
    '강북구': 'GANGBUK',
    '도봉구': 'DOBONG',
    '노원구': 'NOWON',
    '은평구': 'EUNPYEONG',
    '서대문구': 'SEODAEMUN',
    '마포구': 'MAPO',
    '양천구': 'YANGCHEON',
    '강서구': 'GANGSEO',
    '구로구': 'GURO',
    '금천구': 'GEUMCHEON',
    '영등포구': 'YEONGDEUNGPO',
    '동작구': 'DONGJAK',
    '관악구': 'GWANAK',
    '서초구': 'SEOCHO',
    '강남구': 'GANGNAM',
    '송파구': 'SONGPA',
    '강동구': 'GANGDONG',
    '수원': 'SUWON',
    '성남': 'SEONGNAM',
    '고양': 'GOYANG',
    '용인': 'YONGIN',
    '부천': 'BUCHEON',
    '안산': 'ANSAN',
    '안양': 'ANYANG',
    '남양주': 'NAMYANGJU',
    '화성': 'HWASEONG',
    '평택': 'PYEONGTAEK',
    '의정부': 'UIJEONGBU',
    '시흥': 'SIHEUNG',
    '파주': 'PAJU',
    '김포': 'GIMPO',
    '광명': 'GWANGMYEONG',
    '광주': 'GWANGJU_GG',
    '군포': 'GUNPO',
    '하남': 'HANAM',
    '오산': 'OSAN',
    '이천': 'ICHEON',
    '양주': 'YANGJU',
    '안성': 'ANSEONG',
    '구리': 'GURI',
    '포천': 'POCHEON',
    '의왕': 'UIWANG',
    '여주': 'YEOJU',
    '동두천': 'DONGDUCHEON',
    '가평': 'GAPYEONG',
    '양평': 'YANGPYEONG',
    '연천': 'YEONCHEON',
    '과천': 'GWACHEON',
}